### PR TITLE
Add oxygen default template - tiles

### LINKED ISSUE #38: Include OxygenXML project & template in repo.
I have to make a `properties` change for the transformation to work on my PC.

I also expect we will make modifications to the template to suit our export.  So, we should include a template in a `templates` sub-folder of `DITA`, with a readme.txt that explains how to add that template folder to oxygenXML:

https://www.oxygenxml.com/doc/versions/25.1/ug-editor/topics/whr-pt-feature-gallery.html#whr-pt-feature-gallery__custom_templates

### PR DESCRIPTION
**Pull request by brahnavank**
fixes #38
Add oxygen default template (tiles)

### CODE REVIEW

**Comment by IanMayo** [comment]
I need more than this, please.  I want the `project` to be in git.  That will include all project settings.  It will also include the `scenario` as well as the template to be used for export.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Do you need to delete the content that _isn't_ stored in the project folder?

Hmm, maybe we don't need the `project` folder?

Maybe the `project.xpr` file just sits at the top level in `dita`.

**Comment by brahnavank** [comment]
> Do you need to delete the content that _isn't_ stored in the project folder?
> 
> Hmm, maybe we don't need the `project` folder?
> 
> Maybe the `project.xpr` file just sits at the top level in `dita`.

Updated

**Comment by IanMayo** [comment]
I don't think we need the template in there twice @brahnavank .  Can't we have the `content` in the top level `dita` folder, instead of in the project?

image

**Comment by brahnavank** [comment]
> I don't think we need the template in there twice @brahnavank . Can't we have the `content` in the top level `dita` folder, instead of in the project?
> 
> image

image

This is the current structure

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
