### PR TITLE
51 Re-introduce index page at root level

### LINKED ISSUE #51: Insert new root level element
Regions is just one part of the document.

So, we shouldn't use it as the root element.

We should create an `index.ditamap` in `dita`, that just contains a link to the `regions.ditamap` file.  If possible, it would also be useful to have a page of welcome content (`index.dita`).

### PR DESCRIPTION
**Pull request by brahnavank**
Fixes #51 
Changes
Clone from recent master 
Create branch 51_new_root_element_new
Apply the changes for root element
Generate new output

### CODE REVIEW

**Comment by IanMayo** [comment]
Not quite right.

`Regions` tile should be on welcome page. Clicking on it goes to the world map.

We currently have an intermediate step we don't need.  We don't need this page:
image

**Comment by IanMayo** [comment]
Hello, @brahnavank - have pushed a commit that removes the top level tier.  Could you review the [commit](https://github.com/DeepBlueCLtd/Fi3ldMan/pull/55/commits/f03cfcb84583a456be0caf9846c146f1b452de73) please?

If it's ok, then please pull the branch to your repo, then re-generate the output and commit the new versions.

**Comment by brahnavank** [comment]
> Hello, @brahnavank - have pushed a commit that removes the top level tier. Could you review the [commit](https://github.com/DeepBlueCLtd/Fi3ldMan/pull/55/commits/f03cfcb84583a456be0caf9846c146f1b452de73) please?
> 
> If it's ok, then please pull the branch to your repo, then re-generate the output and commit the new versions.

Yes also we can remove index.dita

**Comment by IanMayo** [comment]
Ok. Unncecessary files removed. Would appreciate you pulling this branch, re-generating output, then pushing, please.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
