### PR TITLE
Changes to allow users to navigate current page

### LINKED ISSUE #42: Allow users to navigate current page
Each `class` is made up from several standard elements (images, summary, signatures, propulsion, remarks).

Users will want to jump between these sections.   We should either provide:
* an extra level of links in the existing left-hand table of contents
* a floating `navigate this page` panel within the class itself.  Permanently floating at top?

### PR DESCRIPTION
**Pull request by brahnavank**
Fixes #42 
Changes to enable and support floating navigation across the page

### CODE REVIEW

**Review by IanMayo — APPROVED** [review]

**Comment by IanMayo** [comment]
Hey, that was easy :-D

Can you explain how the issue was solved please?

Is it all down to this parameter?   `webhelp.default.collection.type.sequence`

**Comment by brahnavank** [comment]
> Hey, that was easy :-D
> 
> Can you explain how the issue was solved please?
> 
> Is it all down to this parameter? `webhelp.default.collection.type.sequence`

Also need to introduce ID attribute

**Comment by IanMayo** [comment]
> webhelp.default.collection.type.sequence

The above parameter doesn't seem to relate to in-page navigaton menu.  Can you point me to some documentation on it?  Is the nav-box menu location/style part of the template?

Oh, and...  For new items, will OxygenXML generate a unique ID for is?   Aah, I guess it only has to be unique to that document. So, we _could_ use the same id in all `class` documents.

**Review by IanMayo — CHANGES_REQUESTED** [review]
You haven't "switched on" the in-page navigation.  You have supplied the data necessary for the existing in-page navigation control to be displayed.

We also established that we _could_ provide "standard" section IDs for the page, and the in-page navigation would still work.

You are going to update this branch to _prove_ the above standard IDs work.

**Comment by brahnavank** [comment]
> e also established that we _could_ provide "standard" section IDs for the page, and the in-page navigation would still work.
> 
> You are going to update this branch to _prove_ the above standard IDs work.

dont

**Comment by IanMayo** [comment]
Aah, I see DITA has generated a unique id anyway:
image

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
