### PR TITLE
#27 : Introduce image element in class - dtd updated

### LINKED ISSUE #27: Introduce `image` element in `class`
Almost all `class` instances have a block of images.

The pages start with 3 images presented in a horizontal row at the top, though others may be present later on.

We should introduce an optional list of images at the top of the `class` element.

I guess we could have a `compulsory` images element after `summary`, but then the children are optional.  Actually - I like this approach, since the placeholder for the images will always be there when creating a new document.

_maybe_ we should do the same for `propulsion`, `signatures`, `remarks`?

### PR DESCRIPTION
**Pull request by brahnavank**
Changes to update class element
Introducing images elements

Fixes #27

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks. Do we need to specify that `images` can only contain an `image` element?

**Comment by IanMayo** [comment]
Could you use three different images please? Some samples here:
https://github.com/DeepBlueCLtd/LegacyMan/tree/develop/data/Britain_Standalones/Content/Images

**Comment by brahnavank** [comment]
> Could you use three different images please? Some samples here: https://github.com/DeepBlueCLtd/LegacyMan/tree/develop/data/Britain_Standalones/Content/Images

**Comment by brahnavank** [comment]
> Could you use three different images please? Some samples here: https://github.com/DeepBlueCLtd/LegacyMan/tree/develop/data/Britain_Standalones/Content/Images

updated

**Comment by brahnavank** [comment]
> Thanks. Do we need to specify that `images` can only contain an `image` element?

Yes

**Review by IanMayo — CHANGES_REQUESTED** [review]
- include published output
- remove structural comments
- can't the image elements be expressed in more compact way?  `<image/>` instead of `<image></image>`
- we do not need the `images` block under `body`

image

**Comment by IanMayo** [comment]
> It was stated in issue

Sure, we require the `images` element that is at the top of the page. We don't require another `images` in the `body`.

**Comment by brahnavank** [comment]
> 
I guess we could have a compulsory images element after summary, but then the children are optional. Actually - I like this approach, since the placeholder for the images will always be there when creating a new document.

**Comment by IanMayo** [comment]
Aah yes, sorry for the confusion.  I meant the existing one,  _before_ the summary.

* [ ] Please make the children of `body` compulsory - so they are already present in new documents, and when we port the legacy data.  On publish we'll have to omit the element if it is empty.
image

**Comment by brahnavank** [comment]
> Aah yes, sorry for the confusion. I meant the existing one, _before_ the summary.
> 
> * [ ]  Please make the children of `body` compulsory - so they are already present in new documents, and when we port the legacy data.  On publish we'll have to omit the element if it is empty.
>   image

Changes done, output generated and update.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
