### PR TITLE
Change relative path to the project template

### LINKED ISSUE #48: Project/Scenario/Template not working as expected
I recorded a demo of edit/publish this morning:
https://i.gyazo.com/1d35a6af2163886dda51396bf19d43c8.mp4

But, to do it, I had to delete then re-create the scenario.  I _think_ the project is referring to a scenario on a hard-coded path on your local machine.

You could test this by:
- close oxygenXML
- rename `dita` folder to `dita2`
- open the folder
- open project.xpr
- run the transform/publish

For me the transform failed.  The error dialog included the path it couldn't find.  _Maybe_ we can edit the `.xpr` in the XML editor, find the absolute path, and change it to a relative path.

If the above works, you should be able to rename `dita2` to `dita3` and the publish should work.

### PR DESCRIPTION
**Pull request by brahnavank**
Fixes #48 
Change to fix relative path to project template

### CODE REVIEW

**Comment by IanMayo** [comment]
not quite. Note the warning in the first image.  It appears `cfd` isn't being replaced.

image

image

**Comment by brahnavank** [comment]
> not quite. Note the warning in the first image. It appears `cfd` isn't being replaced.
> 
> image
> 
> image

could you please run and see

**Comment by IanMayo** [comment]
> could you please run and see

image

Note: I first observed the issue when trying to save the `scenario`, after adding that security parameter:
image

**Comment by brahnavank** [comment]
> > could you please run and see
> 
> image
> 
> Note: I first observed the issue when trying to save the `scenario`, after adding that security parameter: image

could you please check now

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
