### PR TITLE
51. Add index page and restructure

### LINKED ISSUE #51: Insert new root level element
Regions is just one part of the document.

So, we shouldn't use it as the root element.

We should create an `index.ditamap` in `dita`, that just contains a link to the `regions.ditamap` file.  If possible, it would also be useful to have a page of welcome content (`index.dita`).

### PR DESCRIPTION
**Pull request by brahnavank**
Fixed #51  
Root element added and correct reference and restructure
Output added

### CODE REVIEW

**Comment by IanMayo** [comment]
I don't think we need the index folder. hopefully it's just index Dita and ditamap at the top level.

**Comment by brahnavank** [comment]
> I don't think we need the index folder. hopefully it's just index Dita and ditamap at the top level.

updated

**Comment by IanMayo** [comment]
Not quite right. We have two levels of 'home' (see screenshot).

I'll be ok with the home page containing the 'regions' tile.

This will contain other tiles too, in the future.

I _guess_ we're returning to the previous output format, but I'm keen that we put 'regions.xxx' into the 'regions' folder, and have some other 'parent' entity in the top-level.

**Comment by brahnavank** [comment]
> Not quite right. We have two levels of 'home' (see screenshot).
> 
> I'll be ok with the home page containing the 'regions' tile.
> 
> This will contain other tiles too, in the future.
> 
> I _guess_ we're returning to the previous output format, but I'm keen that we put 'regions.xxx' into the 'regions' folder, and have some other 'parent' entity in the top-level.
> 
> https://ibb.co/syFKJxg

image

The first home is by default it is coming.

Above one is and old output

**Review by IanMayo — APPROVED** [review]
Great!

**Comment by IanMayo** [comment]
Aah, @brahnavank - I'm going to need you to re-do the output for this branch and commit it, please. The output will be a product of this PR _and_ the props-to-row PR.

**Comment by brahnavank** [comment]
These changes applied in the new branch [51_new_root_element_new](https://github.com/DeepBlueCLtd/Fi3ldMan/tree/51_new_root_element_new)

**Pull request closed without merging**
